"""initial schema

Revision ID: d6049c5192e5
Revises: 
Create Date: 2026-09-26 14:05:56.870455
"""
from alembic import op
import sqlalchemy as sa
from globaltalk.models import GUID


revision = 'd6049c5192e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=True),
    sa.Column('human_source_language', sa.String(length=16), nullable=False),
    sa.Column('agents', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_org_id'), ['org_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=True),
    sa.Column('actor_user_id', GUID(length=36), nullable=True),
    sa.Column('actor_api_key_id', GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_audit_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('billing_events',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_org_id'), ['org_id'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flags_org_id'), ['org_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=True),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_org_id'), ['org_id'], unique=False)

    op.create_table('glossaries',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossaries_org_id'), ['org_id'], unique=False)

    op.create_table('integrations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secret_ref', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_org_id'), ['org_id'], unique=False)

    op.create_table('language_capabilities',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=False),
    sa.Column('speech_input_supported', sa.Boolean(), nullable=False),
    sa.Column('speech_output_supported', sa.Boolean(), nullable=False),
    sa.Column('translation_supported', sa.Boolean(), nullable=False),
    sa.Column('realtime_supported', sa.Boolean(), nullable=False),
    sa.Column('document_supported', sa.Boolean(), nullable=False),
    sa.Column('stt_status', sa.String(length=16), nullable=False),
    sa.Column('tts_status', sa.String(length=16), nullable=False),
    sa.Column('mt_status', sa.String(length=16), nullable=False),
    sa.Column('stt_provider', sa.String(length=60), nullable=False),
    sa.Column('tts_provider', sa.String(length=60), nullable=False),
    sa.Column('mt_provider', sa.String(length=60), nullable=False),
    sa.Column('tts_voices', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('language_pair_validations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('metric_scores', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'target', 'task', name='uq_pair_task')
    )
    with op.batch_alter_table('language_pair_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_pair_validations_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_language_pair_validations_target'), ['target'], unique=False)

    op.create_table('memory_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('memory_class', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source_segment_id', GUID(length=36), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index('ix_memory_scope', ['org_id', 'memory_class', 'scope_id'], unique=False)

    op.create_table('model_registry',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.String(length=80), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('hardware', sa.String(length=20), nullable=False),
    sa.Column('quantization', sa.String(length=20), nullable=False),
    sa.Column('license', sa.String(length=80), nullable=False),
    sa.Column('license_review_status', sa.String(length=20), nullable=False),
    sa.Column('production_status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('latency_p50_ms', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('gpu_required', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_registry_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_registry_task'), ['task'], unique=False)

    op.create_table('organizations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('retention_policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('quality_evaluations',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('passed_gate', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_profiles',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('prompt_fragment', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_profiles_org_id'), ['org_id'], unique=False)

    op.create_table('translation_history',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('glossary_id', GUID(length=36), nullable=True),
    sa.Column('style_profile_id', GUID(length=36), nullable=True),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('from_tm', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_history_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_history_user_id'), ['user_id'], unique=False)

    op.create_table('translation_memories',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('tm_namespace', sa.String(length=120), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('source_norm_hash', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.create_index('ix_tm_lookup', ['org_id', 'source_language', 'target_language', 'source_norm_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memories_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memories_source_norm_hash'), ['source_norm_hash'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('api_key_id', GUID(length=36), nullable=True),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=True),
    sa.Column('document_id', GUID(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_org_time', ['org_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token_hash', sa.String(length=64), nullable=True),
    sa.Column('password_reset_token_hash', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhooks',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('signing_secret', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_org_id'), ['org_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)

    op.create_table('documents',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('detected_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('glossary_id', GUID(length=36), nullable=True),
    sa.Column('style_profile_id', GUID(length=36), nullable=True),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_key', sa.String(length=300), nullable=False),
    sa.Column('output_key', sa.String(length=300), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('segments_total', sa.Integer(), nullable=False),
    sa.Column('segments_done', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('versions_used', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('glossary_terms',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('glossary_id', GUID(length=36), nullable=False),
    sa.Column('source_term', sa.String(length=400), nullable=False),
    sa.Column('source_lower', sa.String(length=400), nullable=False),
    sa.Column('target_term', sa.String(length=400), nullable=False),
    sa.Column('part_of_speech', sa.String(length=30), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('do_not_translate', sa.Boolean(), nullable=False),
    sa.Column('spoken_variants', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_terms_glossary_id'), ['glossary_id'], unique=False)
        batch_op.create_index('ix_gterm_lookup', ['glossary_id', 'source_lower'], unique=False)

    op.create_table('meetings',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('project_id', GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', GUID(length=36), nullable=False),
    sa.Column('room_name', sa.String(length=120), nullable=False),
    sa.Column('join_token', sa.String(length=64), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_join_token'), ['join_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_meetings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_room_name'), ['room_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_meetings_status'), ['status'], unique=False)

    op.create_table('organization_members',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_user')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_org_id'), ['org_id'], unique=True)

    op.create_table('voice_consents',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_audio_key', sa.String(length=300), nullable=True),
    sa.Column('synthetic_flag_metadata', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_consents_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_consents_user_id'), ['user_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('webhook_id', GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('document_jobs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('document_id', GUID(length=36), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_status'), ['status'], unique=False)

    op.create_table('document_segments',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('document_id', GUID(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('translatable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_segments_document_id'), ['document_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('identity', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_identity'), ['identity'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('session_id', GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('translation_segments',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=True),
    sa.Column('source_segment_id', GUID(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('glossary_version', sa.String(length=64), nullable=True),
    sa.Column('style_profile_version', sa.String(length=64), nullable=True),
    sa.Column('from_translation_memory', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('tts_audio_key', sa.String(length=300), nullable=True),
    sa.Column('tts_provider', sa.String(length=60), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_segment_id', 'target_language', name='uq_source_target')
    )
    with op.batch_alter_table('translation_segments', schema=None) as batch_op:
        batch_op.create_index('ix_translation_meeting', ['meeting_id', 'target_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_source_segment_id'), ['source_segment_id'], unique=False)

    op.create_table('audio_sessions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('participant_id', GUID(length=36), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stt_provider', sa.String(length=60), nullable=False),
    sa.Column('latency_mode', sa.String(length=24), nullable=False),
    sa.Column('audio_seconds', sa.Float(), nullable=False),
    sa.Column('dropouts', sa.Integer(), nullable=False),
    sa.Column('reconnects', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_sessions_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_sessions_participant_id'), ['participant_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('participant_id', GUID(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_participant_id'), ['participant_id'], unique=False)

    op.create_table('participant_preferences',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('participant_id', GUID(length=36), nullable=False),
    sa.Column('speaking_language', sa.String(length=16), nullable=False),
    sa.Column('listening_language', sa.String(length=16), nullable=False),
    sa.Column('audio_mode', sa.String(length=16), nullable=False),
    sa.Column('captions_language', sa.String(length=16), nullable=False),
    sa.Column('caption_mode', sa.String(length=16), nullable=False),
    sa.Column('latency_mode', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_preferences_participant_id'), ['participant_id'], unique=True)

    op.create_table('transcript_segments',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('org_id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('participant_id', GUID(length=36), nullable=False),
    sa.Column('audio_session_id', GUID(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.String(length=60), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stt_provider', sa.String(length=60), nullable=False),
    sa.Column('stt_model', sa.String(length=120), nullable=False),
    sa.Column('started_at_ms', sa.Integer(), nullable=False),
    sa.Column('ended_at_ms', sa.Integer(), nullable=False),
    sa.Column('audio_key', sa.String(length=300), nullable=True),
    sa.Column('latency', sa.JSON(), nullable=False),
    sa.Column('correction_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_meeting_seq', ['meeting_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_participant_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_org_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_meeting_id'))
        batch_op.drop_index('ix_transcript_meeting_seq')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('participant_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_preferences_participant_id'))

    op.drop_table('participant_preferences')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_participant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_org_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_meeting_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('audio_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_sessions_participant_id'))
        batch_op.drop_index(batch_op.f('ix_audio_sessions_meeting_id'))

    op.drop_table('audio_sessions')
    with op.batch_alter_table('translation_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_segments_source_segment_id'))
        batch_op.drop_index(batch_op.f('ix_translation_segments_org_id'))
        batch_op.drop_index(batch_op.f('ix_translation_segments_meeting_id'))
        batch_op.drop_index('ix_translation_meeting')

    op.drop_table('translation_segments')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_status'))
        batch_op.drop_index(batch_op.f('ix_participants_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_participants_identity'))

    op.drop_table('participants')
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_segments_document_id'))

    op.drop_table('document_segments')
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_document_id'))

    op.drop_table('document_jobs')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_webhook_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('voice_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_voice_consents_org_id'))

    op.drop_table('voice_consents')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_org_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_org_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_status'))
        batch_op.drop_index(batch_op.f('ix_meetings_room_name'))
        batch_op.drop_index(batch_op.f('ix_meetings_org_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_join_token'))

    op.drop_table('meetings')
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index('ix_gterm_lookup')
        batch_op.drop_index(batch_op.f('ix_glossary_terms_glossary_id'))

    op.drop_table('glossary_terms')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_org_id'))
        batch_op.drop_index(batch_op.f('ix_documents_checksum_sha256'))

    op.drop_table('documents')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_org_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_org_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_dimension'))
        batch_op.drop_index('ix_usage_org_time')

    op.drop_table('usage_records')
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_memories_source_norm_hash'))
        batch_op.drop_index(batch_op.f('ix_translation_memories_org_id'))
        batch_op.drop_index('ix_tm_lookup')

    op.drop_table('translation_memories')
    with op.batch_alter_table('translation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_translation_history_org_id'))

    op.drop_table('translation_history')
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_profiles_org_id'))

    op.drop_table('style_profiles')
    op.drop_table('quality_evaluations')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_registry_task'))
        batch_op.drop_index(batch_op.f('ix_model_registry_provider'))

    op.drop_table('model_registry')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_scope')
        batch_op.drop_index(batch_op.f('ix_memory_items_scope_id'))
        batch_op.drop_index(batch_op.f('ix_memory_items_org_id'))

    op.drop_table('memory_items')
    with op.batch_alter_table('language_pair_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_pair_validations_target'))
        batch_op.drop_index(batch_op.f('ix_language_pair_validations_source'))

    op.drop_table('language_pair_validations')
    op.drop_table('language_capabilities')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_org_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('glossaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossaries_org_id'))

    op.drop_table('glossaries')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_org_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_org_id'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_name'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_org_id'))

    op.drop_table('billing_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_org_id'))

    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
