"""initial schema

Revision ID: eae02319e4b2
Revises: 
Create Date: 2026-09-25 15:53:42.345407
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401  (TZDateTime type)


revision = 'eae02319e4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled_default', sa.Boolean(), nullable=False),
    sa.Column('org_overrides_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('language_capabilities',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=False),
    sa.Column('script', sa.String(length=16), nullable=False),
    sa.Column('rtl', sa.Boolean(), nullable=False),
    sa.Column('translation_status', sa.String(length=16), nullable=False),
    sa.Column('speech_input_status', sa.String(length=16), nullable=False),
    sa.Column('speech_output_status', sa.String(length=16), nullable=False),
    sa.Column('realtime_status', sa.String(length=16), nullable=False),
    sa.Column('document_status', sa.String(length=16), nullable=False),
    sa.Column('stt_provider', sa.String(length=64), nullable=False),
    sa.Column('mt_provider', sa.String(length=64), nullable=False),
    sa.Column('tts_provider', sa.String(length=64), nullable=False),
    sa.Column('tts_voices', sa.JSON(), nullable=False),
    sa.Column('wer_benchmark', sa.Float(), nullable=True),
    sa.Column('mt_quality_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('language_pair_capabilities',
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('bleu_score', sa.Float(), nullable=True),
    sa.Column('latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('evaluated_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('eval_report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_lang', 'target_lang', 'domain')
    )
    op.create_table('model_registry',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('quality_tier', sa.Integer(), nullable=False),
    sa.Column('cost_tier', sa.Integer(), nullable=False),
    sa.Column('latency_class', sa.String(length=16), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('requires_gpu', sa.Boolean(), nullable=False),
    sa.Column('languages_json', sa.JSON(), nullable=True),
    sa.Column('validated_pairs_json', sa.JSON(), nullable=False),
    sa.Column('domains_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_registry_task'), ['task'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('retention_json', sa.JSON(), nullable=False),
    sa.Column('deleted_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('speak_lang', sa.String(length=16), nullable=False),
    sa.Column('hear_lang', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_used_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)

    op.create_table('audit_logs',
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_kind', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_audit_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('billing_events',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('lines_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_org_id'), ['org_id'], unique=False)

    op.create_table('feedback',
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('correction_text', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_target_id'), ['target_id'], unique=False)

    op.create_table('integrations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('credentials_ref', sa.String(length=200), nullable=False),
    sa.Column('last_sync_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_org_id'), ['org_id'], unique=False)

    op.create_table('organization_members',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','manager','member','viewer')", name='ck_member_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_user')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_glossary_id', sa.Uuid(), nullable=True),
    sa.Column('default_style_profile_id', sa.Uuid(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)

    op.create_table('quality_evaluations',
    sa.Column('pair', sa.String(length=40), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('n_cases', sa.Integer(), nullable=False),
    sa.Column('bleu_avg', sa.Float(), nullable=True),
    sa.Column('wer_avg', sa.Float(), nullable=True),
    sa.Column('cer_avg', sa.Float(), nullable=True),
    sa.Column('latency_p95_ms', sa.Float(), nullable=True),
    sa.Column('failure_rate', sa.Float(), nullable=True),
    sa.Column('passed_gates', sa.Boolean(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('evaluated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_evaluations_pair'), ['pair'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_info', sa.String(length=300), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('style_profiles',
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_profiles_org_id'), ['org_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('quota_json', sa.JSON(), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('translation_memories',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_memories_org_id'), ['org_id'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_org_id'), ['org_id'], unique=False)

    op.create_table('glossaries',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossaries_org_id'), ['org_id'], unique=False)

    op.create_table('meetings',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('room_name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('retention_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('next_seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_room_name'), ['room_name'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('translation_memory_entries',
    sa.Column('tm_id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_normalized', sa.String(length=64), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tm_id'], ['translation_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memory_entries', schema=None) as batch_op:
        batch_op.create_index('ix_tme_lookup', ['tm_id', 'source_lang', 'target_lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memory_entries_source_normalized'), ['source_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memory_entries_tm_id'), ['tm_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('product', sa.String(length=20), nullable=False),
    sa.Column('unit_type', sa.String(length=30), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_org_time', ['org_id', 'created_at'], unique=False)
        batch_op.create_index('ix_usage_product', ['product', 'unit_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_request_id'), ['request_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_endpoint_id'), ['endpoint_id'], unique=False)

    op.create_table('agent_sessions',
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_lang', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bridge_state_json', sa.JSON(), nullable=False),
    sa.Column('consumed_seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_sessions_org_id'), ['org_id'], unique=False)

    op.create_table('documents',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('detected_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('glossary_id', sa.Uuid(), nullable=True),
    sa.Column('style_profile_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_object_key', sa.String(length=500), nullable=False),
    sa.Column('output_object_key', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('glossary_version', sa.Integer(), nullable=True),
    sa.Column('style_version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('ready_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['style_profile_id'], ['style_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('glossary_terms',
    sa.Column('glossary_id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sa.String(length=500), nullable=False),
    sa.Column('target_text', sa.String(length=500), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('spoken_variants_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('glossary_id', 'source_text', name='uq_glossary_term')
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_terms_glossary_id'), ['glossary_id'], unique=False)

    op.create_table('memory_items',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('memory_class', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('expires_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("memory_class IN ('working','semantic','episodic','procedural','retrieval','parametric','prospective')", name='ck_memory_class'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_memory_scope', ['org_id', 'meeting_id', 'memory_class'], unique=False)

    op.create_table('participants',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('left_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('livekit_identity', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', 'guest_key', name='uq_meeting_user')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_user_id'), ['user_id'], unique=False)

    op.create_table('audio_sessions',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('audio_object_key', sa.String(length=500), nullable=True),
    sa.Column('latency_json', sa.JSON(), nullable=False),
    sa.Column('reconnect_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_sessions_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_sessions_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('chat_messages',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('detected_lang', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('translations_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_meeting_created', ['meeting_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('document_jobs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('started_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_jobs_document_id'), ['document_id'], unique=False)

    op.create_table('document_segments',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('font_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.create_index('ix_docseg_doc_idx', ['document_id', 'block_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_segments_document_id'), ['document_id'], unique=False)

    op.create_table('participant_preferences',
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('speak_lang', sa.String(length=16), nullable=False),
    sa.Column('hear_lang', sa.String(length=16), nullable=False),
    sa.Column('audio_mode', sa.String(length=20), nullable=False),
    sa.Column('captions_enabled', sa.Boolean(), nullable=False),
    sa.Column('ducking_level', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("audio_mode IN ('original','translated','mixed','captions_only')", name='ck_audio_mode'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', name='uq_pref_participant')
    )
    with op.batch_alter_table('participant_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_preferences_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_preferences_participant_id'), ['participant_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('speaker_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_name', sa.String(length=200), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=True),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('stt_model', sa.String(length=100), nullable=False),
    sa.Column('stt_provider', sa.String(length=64), nullable=False),
    sa.Column('audio_object_key', sa.String(length=500), nullable=True),
    sa.Column('correction_status', sa.String(length=20), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('latency_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'seq', name='uq_meeting_seq')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_meeting_created', ['meeting_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('translation_segments',
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('product', sa.String(length=20), nullable=False),
    sa.Column('source_lang', sa.String(length=16), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('quality_flags_json', sa.JSON(), nullable=False),
    sa.Column('glossary_id', sa.Uuid(), nullable=True),
    sa.Column('glossary_version', sa.Integer(), nullable=True),
    sa.Column('style_profile_id', sa.Uuid(), nullable=True),
    sa.Column('tm_id', sa.Uuid(), nullable=True),
    sa.Column('tm_match_type', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_profile_id'], ['style_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tm_id'], ['translation_memories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'target_lang', name='uq_segment_target')
    )
    with op.batch_alter_table('translation_segments', schema=None) as batch_op:
        batch_op.create_index('ix_translation_product_created', ['product', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_segments_target_lang'), ['target_lang'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_segments_target_lang'))
        batch_op.drop_index(batch_op.f('ix_translation_segments_segment_id'))
        batch_op.drop_index(batch_op.f('ix_translation_segments_org_id'))
        batch_op.drop_index(batch_op.f('ix_translation_segments_meeting_id'))
        batch_op.drop_index('ix_translation_product_created')

    op.drop_table('translation_segments')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_meeting_id'))
        batch_op.drop_index('ix_segments_meeting_created')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('participant_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_preferences_participant_id'))
        batch_op.drop_index(batch_op.f('ix_participant_preferences_meeting_id'))

    op.drop_table('participant_preferences')
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_segments_document_id'))
        batch_op.drop_index('ix_docseg_doc_idx')

    op.drop_table('document_segments')
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_jobs_document_id'))

    op.drop_table('document_jobs')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_meeting_id'))
        batch_op.drop_index('ix_chat_meeting_created')

    op.drop_table('chat_messages')
    with op.batch_alter_table('audio_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_sessions_session_key'))
        batch_op.drop_index(batch_op.f('ix_audio_sessions_participant_id'))
        batch_op.drop_index(batch_op.f('ix_audio_sessions_meeting_id'))

    op.drop_table('audio_sessions')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_participants_meeting_id'))

    op.drop_table('participants')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_scope')
        batch_op.drop_index(batch_op.f('ix_memory_items_org_id'))
        batch_op.drop_index(batch_op.f('ix_memory_items_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_memory_items_key'))

    op.drop_table('memory_items')
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_terms_glossary_id'))

    op.drop_table('glossary_terms')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_org_id'))
        batch_op.drop_index(batch_op.f('ix_documents_checksum'))

    op.drop_table('documents')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_sessions_meeting_id'))

    op.drop_table('agent_sessions')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_endpoint_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_org_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_created_at'))
        batch_op.drop_index('ix_usage_product')
        batch_op.drop_index('ix_usage_org_time')

    op.drop_table('usage_records')
    with op.batch_alter_table('translation_memory_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_memory_entries_tm_id'))
        batch_op.drop_index(batch_op.f('ix_translation_memory_entries_source_normalized'))
        batch_op.drop_index('ix_tme_lookup')

    op.drop_table('translation_memory_entries')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_session_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_room_name'))
        batch_op.drop_index(batch_op.f('ix_meetings_org_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('glossaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossaries_org_id'))

    op.drop_table('glossaries')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_org_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_memories_org_id'))

    op.drop_table('translation_memories')
    op.drop_table('subscriptions')
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_profiles_org_id'))

    op.drop_table('style_profiles')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('quality_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_evaluations_pair'))

    op.drop_table('quality_evaluations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_org_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_org_id'))

    op.drop_table('integrations')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_target_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_org_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_org_id'))

    op.drop_table('billing_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_registry_task'))

    op.drop_table('model_registry')
    op.drop_table('language_pair_capabilities')
    op.drop_table('language_capabilities')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
