-- =====================================================================
-- TalkFlow / GlobalTalk AI Schema Definition (PostgreSQL)
-- Generated by /replica-architect for replica pack
-- =====================================================================

create extension if not exists "uuid-ossp";

-- 1. Organizations (Workspaces / Multi-tenant boundary)
create table organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  plan text not null default 'free' check (plan in ('free', 'pro', 'enterprise')),
  seat_limit integer not null default 5,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_organizations_slug on organizations(slug);

-- 2. Users & Memberships
create table users (
  id uuid primary key default gen_random_uuid(),
  org_id uuid references organizations(id) on delete cascade,
  email text not null unique,
  hashed_password text not null,
  full_name text not null,
  avatar_url text,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  preferred_language text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_users_org on users(org_id);
create index idx_users_email on users(email);

-- 3. API Keys (Developer access & integrations)
create table api_keys (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  created_by uuid not null references users(id) on delete cascade,
  name text not null,
  key_prefix text not null,
  hashed_key text not null,
  rate_limit_rpm integer not null default 60,
  last_used_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create index idx_api_keys_org on api_keys(org_id);
create index idx_api_keys_prefix on api_keys(key_prefix);

-- 4. Meetings & Sessions
create table meetings (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  host_id uuid not null references users(id) on delete cascade,
  room_name text not null unique,
  title text not null default 'Instant Meeting',
  scheduled_at timestamptz not null default now(),
  duration_mins integer not null default 30,
  status text not null default 'scheduled' check (status in ('scheduled', 'active', 'ended', 'cancelled')),
  allow_guests boolean not null default true,
  settings jsonb not null default '{"source_lang": "auto", "default_target_lang": "en", "record_audio": true, "enable_transcripts": true}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_meetings_org on meetings(org_id);
create index idx_meetings_host on meetings(host_id);
create index idx_meetings_room_name on meetings(room_name);
create index idx_meetings_status on meetings(status);

-- 5. Meeting Participants (Registered users or Public guests)
create table meeting_participants (
  id uuid primary key default gen_random_uuid(),
  meeting_id uuid not null references meetings(id) on delete cascade,
  user_id uuid references users(id) on delete set null,
  guest_name text,
  target_language text not null default 'en',
  livekit_identity text not null,
  joined_at timestamptz not null default now(),
  left_at timestamptz
);
create index idx_participants_meeting on meeting_participants(meeting_id);
create index idx_participants_user on meeting_participants(user_id);

-- 6. Transcripts & Translated Segments
create table transcripts (
  id uuid primary key default gen_random_uuid(),
  meeting_id uuid references meetings(id) on delete cascade,
  speaker_id text not null,
  speaker_name text not null,
  source_lang text not null,
  target_lang text not null,
  original_text text not null,
  translated_text text not null,
  audio_start_ms bigint not null default 0,
  audio_end_ms bigint not null default 0,
  confidence double precision default 0.95,
  created_at timestamptz not null default now()
);
create index idx_transcripts_meeting on transcripts(meeting_id);
create index idx_transcripts_created on transcripts(created_at);

-- 7. Document Translation Jobs
create table document_jobs (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  file_name text not null,
  file_format text not null check (file_format in ('pdf', 'docx', 'pptx', 'xlsx', 'txt', 'csv')),
  source_lang text not null default 'auto',
  target_lang text not null,
  status text not null default 'pending' check (status in ('pending', 'parsing', 'translating', 'rendering', 'completed', 'failed')),
  input_file_url text not null,
  output_file_url text,
  char_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create index idx_document_jobs_org on document_jobs(org_id);
create index idx_document_jobs_user on document_jobs(user_id);
create index idx_document_jobs_status on document_jobs(status);

-- 8. Custom Glossaries & Terminology
create table glossaries (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  name text not null,
  source_lang text not null,
  target_lang text not null,
  terms jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_glossaries_org on glossaries(org_id);

-- 9. Translation Memory (Bilingual Segment Cache)
create table translation_memories (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references organizations(id) on delete cascade,
  source_lang text not null,
  target_lang text not null,
  source_segment text not null,
  target_segment text not null,
  match_count integer not null default 1,
  created_at timestamptz not null default now(),
  constraint unique_org_segment unique (org_id, source_lang, target_lang, source_segment)
);
create index idx_tm_org on translation_memories(org_id);
create index idx_tm_lookup on translation_memories(org_id, source_lang, target_lang);

-- 10. Subscriptions & Billing Ledger
create table subscriptions (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null unique references organizations(id) on delete cascade,
  stripe_customer_id text not null,
  stripe_subscription_id text,
  plan_tier text not null default 'free' check (plan_tier in ('free', 'pro', 'enterprise')),
  status text not null default 'active' check (status in ('active', 'past_due', 'canceled', 'trialing')),
  monthly_audio_minutes_limit integer not null default 60,
  monthly_characters_limit integer not null default 100000,
  current_period_start timestamptz not null default now(),
  current_period_end timestamptz not null default (now() + interval '30 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_subscriptions_org on subscriptions(org_id);
