// Supported Languages for Amazon Connect Desi Voice-to-Voice AI
// Supports 100+ World Languages and all 22 official Eighth Schedule Indian Languages

export const INDIC_LANGUAGES = [
  { language: "hi", name: "Hindi (हिन्दी)", script: "Devanagari", family: "Indo-Aryan" },
  { language: "bn", name: "Bengali (বাংলা)", script: "Bengali", family: "Indo-Aryan" },
  { language: "te", name: "Telugu (తెలుగు)", script: "Telugu", family: "Dravidian" },
  { language: "mr", name: "Marathi (मराठी)", script: "Devanagari", family: "Indo-Aryan" },
  { language: "ta", name: "Tamil (தமிழ்)", script: "Tamil", family: "Dravidian" },
  { language: "ur", name: "Urdu (اردو)", script: "Perso-Arabic", family: "Indo-Aryan" },
  { language: "gu", name: "Gujarati (ગુજરાતી)", script: "Gujarati", family: "Indo-Aryan" },
  { language: "kn", name: "Kannada (ಕನ್ನಡ)", script: "Kannada", family: "Dravidian" },
  { language: "ml", name: "Malayalam (മലയാളം)", script: "Malayalam", family: "Dravidian" },
  { language: "or", name: "Odia (ଓଡ଼ିଆ)", script: "Odia", family: "Indo-Aryan" },
  { language: "pa", name: "Punjabi (ਪੰਜਾਬੀ)", script: "Gurmukhi", family: "Indo-Aryan" },
  { language: "as", name: "Assamese (অসমীয়া)", script: "Bengali-Assamese", family: "Indo-Aryan" },
  { language: "mai", name: "Maithili (मैथिली)", script: "Devanagari", family: "Indo-Aryan" },
  { language: "sat", name: "Santali (ᱥᱟᱱᱛᱟᱲᱤ)", script: "Ol Chiki", family: "Austroasiatic" },
  { language: "ks", name: "Kashmiri (کٲشُر)", script: "Perso-Arabic", family: "Dardic" },
  { language: "ne", name: "Nepali (नेपाली)", script: "Devanagari", family: "Indo-Aryan" },
  { language: "sd", name: "Sindhi (سنڌي)", script: "Perso-Arabic", family: "Indo-Aryan" },
  { language: "kok", name: "Konkani (कोंकणी)", script: "Devanagari", family: "Indo-Aryan" },
  { language: "doi", name: "Dogri (डोगरी)", script: "Devanagari", family: "Indo-Aryan" },
  { language: "mni", name: "Manipuri (ꯃꯤꯇꯩꯂꯣꯟ)", script: "Meetei Mayek", family: "Tibeto-Burman" },
  { language: "brx", name: "Bodo (बर')", script: "Devanagari", family: "Tibeto-Burman" },
  { language: "sa", name: "Sanskrit (संस्कृतम्)", script: "Devanagari", family: "Indo-Aryan" }
];

export const SUPPORTED_SOURCE_LANGUAGES = [
  { language: "en", name: "English" },
  { language: "hi", name: "Hindi (हिन्दी)" },
  { language: "es", name: "Spanish (Español)" },
  { language: "fr", name: "French (Français)" },
  { language: "de", name: "German (Deutsch)" },
  { language: "bn", name: "Bengali (বাংলা)" },
  { language: "te", name: "Telugu (తెలుగు)" },
  { language: "mr", name: "Marathi (मराठी)" },
  { language: "ta", name: "Tamil (தமிழ்)" },
  { language: "ur", name: "Urdu (اردو)" },
  { language: "gu", name: "Gujarati (ગુજરાતી)" },
  { language: "kn", name: "Kannada (ಕನ್ನಡ)" },
  { language: "ml", name: "Malayalam (മലയാളം)" },
  { language: "pa", name: "Punjabi (ਪੰਜਾਬੀ)" },
  { language: "it", name: "Italian (Italiano)" },
  { language: "ja", name: "Japanese (日本語)" },
  { language: "ko", name: "Korean (한국어)" },
  { language: "zh", name: "Chinese (Simplified - 简体中文)" },
  { language: "zh-Hant", name: "Chinese (Traditional - 繁體中文)" },
  { language: "ar", name: "Arabic (العربية)" },
  { language: "pt", name: "Portuguese (Português)" },
  { language: "ru", name: "Russian (Русский)" },
  { language: "nl", name: "Dutch (Nederlands)" },
  { language: "pl", name: "Polish (Polski)" },
  { language: "tr", name: "Turkish (Türkçe)" },
  { language: "vi", name: "Vietnamese (Tiếng Việt)" },
  { language: "id", name: "Indonesian (Bahasa Indonesia)" },
  { language: "th", name: "Thai (ไทย)" },
  { language: "sv", name: "Swedish (Svenska)" },
  { language: "uk", name: "Ukrainian (Українська)" }
];

export const SUPPORTED_TARGET_LANGUAGES = [
  ...INDIC_LANGUAGES,
  { language: "en", name: "English" },
  { language: "en-US", name: "English (American)" },
  { language: "en-GB", name: "English (British)" },
  { language: "es", name: "Spanish (Español)" },
  { language: "fr", name: "French (Français)" },
  { language: "de", name: "German (Deutsch)" },
  { language: "it", name: "Italian (Italiano)" },
  { language: "ja", name: "Japanese (日本語)" },
  { language: "ko", name: "Korean (한국어)" },
  { language: "zh-Hans", name: "Chinese (Simplified)" },
  { language: "zh-Hant", name: "Chinese (Traditional)" },
  { language: "ar", name: "Arabic (العربية)" },
  { language: "pt-BR", name: "Portuguese (Brazilian)" },
  { language: "pt-PT", name: "Portuguese (European)" },
  { language: "ru", name: "Russian (Русский)" },
  { language: "nl", name: "Dutch (Nederlands)" },
  { language: "pl", name: "Polish (Polski)" },
  { language: "tr", name: "Turkish (Türkçe)" },
  { language: "vi", name: "Vietnamese (Tiếng Việt)" },
  { language: "id", name: "Indonesian (Bahasa Indonesia)" },
  { language: "th", name: "Thai (ไทย)" },
  { language: "sv", name: "Swedish (Svenska)" },
  { language: "da", name: "Danish (Dansk)" },
  { language: "fi", name: "Finnish (Suomi)" },
  { language: "el", name: "Greek (Ελληνικά)" },
  { language: "cs", name: "Czech (Čeština)" },
  { language: "hu", name: "Hungarian (Magyar)" },
  { language: "ro", name: "Romanian (Română)" },
  { language: "uk", name: "Ukrainian (Українська)" },
  { language: "he", name: "Hebrew (עברית)" }
];
