"""harmonize_schema_models

Revision ID: 2202ca7dc080
Revises: eae02319e4b2
Create Date: 2026-10-06 18:35:21.956177
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import app.db.base  # noqa: F401


revision = '2202ca7dc080'
down_revision = 'eae02319e4b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_prompts',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('agent_role', sa.String(length=120), nullable=False),
    sa.Column('active_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_prompts_org_id'), ['org_id'], unique=False)

    op.create_table('phone_numbers',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('e164_number', sa.String(length=32), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('friendly_name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_sid', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('assigned_agent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_numbers_e164_number'), ['e164_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_phone_numbers_org_id'), ['org_id'], unique=False)

    op.create_table('user_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_identities_user_provider', ['user_id', 'provider'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('agent_prompt_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_platform_prompt', sa.Text(), nullable=False),
    sa.Column('original_custom_prompt', sa.Text(), nullable=False),
    sa.Column('project_context', sa.Text(), nullable=False),
    sa.Column('merged_prompt', sa.Text(), nullable=False),
    sa.Column('conflicts_json', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('validation_errors_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_prompt_id'], ['agent_prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_prompt_id', 'version', name='uq_agent_version')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_agent_prompt_id'), ['agent_prompt_id'], unique=False)

    op.create_table('call_sessions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('call_sid', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=False),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('caller_name', sa.String(length=120), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('caller_language', sa.String(length=16), nullable=False),
    sa.Column('receiver_language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('stream_sid', sa.String(length=120), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('connected_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('telephony_cost_cents', sa.Integer(), nullable=False),
    sa.Column('stt_cost_cents', sa.Integer(), nullable=False),
    sa.Column('mt_cost_cents', sa.Integer(), nullable=False),
    sa.Column('tts_cost_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_call_org_created', ['org_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_call_sid'), ['call_sid'], unique=True)
        batch_op.create_index(batch_op.f('ix_call_sessions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_sessions_status'), ['status'], unique=False)
        batch_op.create_index('ix_call_sid', ['call_sid'], unique=False)

    op.create_table('call_events',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index('ix_call_event_call_time', ['call_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_events_call_id'), ['call_id'], unique=False)

    with op.batch_alter_table('language_capabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speech_input_supported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('speech_output_supported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('translation_supported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('realtime_supported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('document_supported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stt_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('tts_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('mt_status', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_capabilities', schema=None) as batch_op:
        batch_op.drop_column('mt_status')
        batch_op.drop_column('tts_status')
        batch_op.drop_column('stt_status')
        batch_op.drop_column('document_supported')
        batch_op.drop_column('realtime_supported')
        batch_op.drop_column('translation_supported')
        batch_op.drop_column('speech_output_supported')
        batch_op.drop_column('speech_input_supported')

    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_events_call_id'))
        batch_op.drop_index('ix_call_event_call_time')

    op.drop_table('call_events')
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_call_sid')
        batch_op.drop_index(batch_op.f('ix_call_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_org_id'))
        batch_op.drop_index(batch_op.f('ix_call_sessions_call_sid'))
        batch_op.drop_index('ix_call_org_created')

    op.drop_table('call_sessions')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_agent_prompt_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_user_identities_user_provider')
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_identities_provider'))

    op.drop_table('user_identities')
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_numbers_org_id'))
        batch_op.drop_index(batch_op.f('ix_phone_numbers_e164_number'))

    op.drop_table('phone_numbers')
    with op.batch_alter_table('agent_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_prompts_org_id'))

    op.drop_table('agent_prompts')
    # ### end Alembic commands ###
